spring:
  application:
    name: kafka-consumer
  cloud:
    stream:
      function:
        definition: squaredNumberConsumer
      bindings:
        squaredNumberConsumer-in-0:
          destination: squaredNumbers
          consumer:
            use-native-decoding: true
      kafka:
        binder:
          brokers:
            brokers:
              - localhost:9090
              - localhost:9091
              - localhost:9092
        bindings:
          squaredNumberConsumer-in-0:
            consumer:
              configuration:
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                  deserializer: org.apache.kafka.common.serialization.LongDeserializer
